name: Build AccessMod pipelines

on:
  pull_request:
    paths:
      - 'accessmod/*'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
  push:
    branches: [main]
    paths:
      - 'accessmod/*'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-entrypoint.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    # see https://github.com/docker/build-push-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Copy production code
        run: |
          cp Dockerfile accessmod/
          cp requirements.txt accessmod/
          cp docker-entrypoint.sh accessmod/
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: ./accessmod/
          tags: |
            blsq/accessmod-pipelines:latest
